In [29]:
import tensorflow as tf
import numpy as np

In [7]:
t = tf.random_normal((4,3))

In [8]:
sess = tf.InteractiveSession()

Exception AssertionError: AssertionError() in <bound method InteractiveSession.__del__ of <tensorflow.python.client.session.InteractiveSession object at 0x7f8d1448e150>> ignored


In [15]:
sess.run([t, tf.arg_max(t, dimension=1)])

[array([[ 0.72746545, -0.68051934,  0.21055566],
        [ 0.85468984, -1.73917162, -1.21599209],
        [ 0.58213192, -0.90190017, -0.64913821],
        [-0.86752349,  0.16742691,  0.84491307]], dtype=float32),
 array([0, 0, 0, 2])]

In [12]:
?tf.arg_max

In [18]:
c = tf.constant(0.5)

In [19]:
sess.run([t, c*t])

[array([[ 0.34724277,  0.6608656 ,  0.43116933],
        [-0.48315111,  0.892003  ,  0.60531151],
        [ 0.17994949,  0.13526289, -0.71118593],
        [ 0.2168636 , -0.0341404 , -1.04781568]], dtype=float32),
 array([[ 0.17362139,  0.3304328 ,  0.21558467],
        [-0.24157555,  0.4460015 ,  0.30265576],
        [ 0.08997475,  0.06763145, -0.35559297],
        [ 0.1084318 , -0.0170702 , -0.52390784]], dtype=float32)]

In [21]:
sess.run([t, tf.reduce_sum(t, reduction_indices=[1,])])

[array([[ 0.46160161, -2.05513716, -2.90273142],
        [-1.03117085, -0.45882538, -0.44779259],
        [-0.61726028, -0.33546519,  0.38373214],
        [ 0.83618456, -0.21057898,  2.06498384]], dtype=float32),
 array([-4.49626684, -1.93778872, -0.56899333,  2.69058943], dtype=float32)]

In [34]:
i = tf.placeholder(tf.int32, (4,))

In [36]:
sess.run(t[i], {i: np.array([0,1,1,1])})

TypeError: Bad slice index Tensor("Placeholder_1:0", shape=TensorShape([Dimension(4)]), dtype=int32) of type <class 'tensorflow.python.framework.ops.Tensor'>

In [45]:
sess.run([t, tf.reduce_max(t, 1)])

[array([[ 0.02137903,  1.23828769,  0.53914273],
        [-1.06534982, -0.21909024, -1.19062781],
        [-0.50089341, -1.03411007,  0.02972561],
        [ 1.17602372,  0.27990618, -1.23782802]], dtype=float32),
 array([ 1.23828769, -0.21909024,  0.02972561,  1.17602372], dtype=float32)]

In [39]:
?tf.train.RMSPropOptimizer

In [46]:
a,b,c = [1,2,3,4,5]

ValueError: too many values to unpack

In [47]:
x = tf.train.SummaryWriter("logs/", sess.graph_def)

In [48]:
?x.add_summary