In [1]:
import tensorflow as tf
import numpy as np

In [2]:
t = tf.random_normal((4,3))

In [3]:
sess = tf.InteractiveSession()

In [4]:
sess.run([t, tf.arg_max(t, dimension=1)])

[array([[ 0.65903568,  0.27294803, -0.25162405],
        [-0.13739336,  1.11778617, -0.59342676],
        [ 0.11897045,  0.2520096 , -0.07296234],
        [-0.70208603,  0.5883683 , -1.31883645]], dtype=float32),
 array([0, 1, 1, 1])]

In [28]:
with tf.name_scope("siema"):
    x=tf.Variable(tf.zeros(2), name="xx")
    y=tf.Variable(tf.zeros(2), name="xx")

In [41]:
?tf.random_normal_initializer

In [6]:
x = tf.get_variable("x6", [1,10], initializer=tf.random_normal_initializer(0., 1.))
sess.run(tf.initialize_all_variables())
x.eval()
x.initialized_value

array([[ 0.64873922, -0.46163663,  0.35025784, -0.49603328, -0.53684181,
         0.3873643 , -1.69296277, -0.67500257,  1.0015502 , -0.09007744]], dtype=float32)

In [18]:
sess.close()
tf.ops.reset_default_graph()
sess = tf.InteractiveSession()

x = tf.Variable(tf.zeros((1,)), name='x')

y = tf.Variable(tf.ones((1,)), name='y')

ass_op = y.assign(x)

c1 = tf.constant(1.0)
c2 = tf.constant(2.0)

obj1 = tf.square(c1 - x)
obj2 = tf.square(c2 - x)

loss = tf.stop_gradient(obj1) + obj2

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
optimize_op = optimizer.minimize(loss)
sess.run(tf.initialize_all_variables())

sess.run(ass_op)
for _ in range(300):
    _ = sess.run(optimize_op)
x.eval(), y.eval()

(array([ 1.99533522], dtype=float32), array([ 0.], dtype=float32))

In [9]:
sess.graph.get_operation_by_name("x")

In [23]:
tf.identity(x, name="Siema")

In [21]:
sess.run([t, tf.reduce_sum(t, reduction_indices=[1,])])

[array([[ 0.46160161, -2.05513716, -2.90273142],
        [-1.03117085, -0.45882538, -0.44779259],
        [-0.61726028, -0.33546519,  0.38373214],
        [ 0.83618456, -0.21057898,  2.06498384]], dtype=float32),
 array([-4.49626684, -1.93778872, -0.56899333,  2.69058943], dtype=float32)]

In [34]:
i = tf.placeholder(tf.int32, (4,))

In [36]:
sess.run(t[i], {i: np.array([0,1,1,1])})

TypeError: Bad slice index Tensor("Placeholder_1:0", shape=TensorShape([Dimension(4)]), dtype=int32) of type <class 'tensorflow.python.framework.ops.Tensor'>

In [45]:
sess.run([t, tf.reduce_max(t, 1)])

[array([[ 0.02137903,  1.23828769,  0.53914273],
        [-1.06534982, -0.21909024, -1.19062781],
        [-0.50089341, -1.03411007,  0.02972561],
        [ 1.17602372,  0.27990618, -1.23782802]], dtype=float32),
 array([ 1.23828769, -0.21909024,  0.02972561,  1.17602372], dtype=float32)]

In [39]:
?tf.train.RMSPropOptimizer

In [46]:
a,b,c = [1,2,3,4,5]

ValueError: too many values to unpack

In [47]:
x = tf.train.SummaryWriter("logs/", sess.graph_def)

In [7]:
p = tf.Print("siema")

sess.run(p)

TypeError: Print() takes at least 2 arguments (1 given)

In [8]:
?tf.Print